### ISSUE TITLE
Difference with jvitor83/typings-autoinstaller ?

### ISSUE THREAD

**Issue by Shuunen** [jvitor83/types-autoinstaller#16]
Hi,

On VsCode there is 2 extensions you created that seems to do the same jobs : 

https://marketplace.visualstudio.com/search?term=publisher%3A%22Jo%C3%A3o%20Vitor%20Paes%20de%20Barros%20do%20Carmo%22&target=VSCode&category=All%20categories&sortBy=Relevance

The oldest one is the most popular :

- Version : 1.2.0
- Last updated : 8/23/2016
- Publisher : João Vitor Paes de Barros do Carmo
- Unique Identifier | jvitor83.typings-autoinstaller 
- https://github.com/jvitor83/typings-autoinstaller 
- https://marketplace.visualstudio.com/items?itemName=jvitor83.typings-autoinstaller

And this one, more recent, less used : 

- Version : 2.3.1
- Last updated : 8/29/2017
- Publisher : João Vitor Paes de Barros do Carmo
- Unique Identifier : jvitor83.types-autoinstaller
- https://github.com/jvitor83/types-autoinstaller
- https://marketplace.visualstudio.com/items?itemName=jvitor83.types-autoinstaller

Both have the same description...

What am I missing?

**Comment by jvitor83** [comment]
Hi @Shuunen,
The Types AutoInstaller extension use the `npm install @types/{your-desired-package} --save-dev`
The Typings AutoInstaller extension use the `typings install {your-desired-package} --save`

Basically the **typings autoinstaller is deprecated**, because it use the [typings (which is a deprecated tool)](https://github.com/typings/typings). But if your project is using the typings, it is the extension you need.

The types-autoinstaller is the one you should use for newer projects.

**Comment by Shuunen** [comment]
Thanks for your answer, it was not clear to me and it is now :+1: 

Is this explanation should be included in both readme ?
